config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  #Home
  # get "/" => "main#index"
  root  "main#index"
  # About 
  get "about" => "about#index"
  #Signup
  get "sign_up"=> "registration#new"
  post "sign_up"=> "registration#create"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# our user model has:
#email: string
#password_digest:string

#Added by "has_secure_password"
#password:string virtial
#password_confirmation: string virtual

class User < ApplicationRecord
    # method that hash the password of user 
    has_secure_password


    validates :email, presence:true

end

app/controllers/about_controller.rb
class AboutController <ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController <ApplicationController
    def index
        flash[:notice] = "Logged in successfully"
        flash[:alert] = "Invalid credentials!"
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>Hello World, this is About page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <%= render partial: "shared/navbar" %>
    <%
=begin%>
 <%= render partial: "shared/flash" %> 
<%
=end%>
    
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center text-red">
    <h1>Hello this is Homepage</h1>
</div>
 

app/views/shared/_flash.html.erb
<div class="alert alert-danger mt-4 mb-0" role="alert">
<%=flash[:alert]%>
</div>
<br>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <%= link_to "Scheduled Tweets", root_path, class:"navbar-brand" %>
    <%
=begin%>
 <a class="navbar-brand" href="/">Scheduled Tweets</a> 
<%
=end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
   <div class="d-flex justify-content-between w-100"> 
     <div> <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
  
        </li>
        <li class="nav-item">
 <%= link_to "About", about_path, class:"nav-link" %>        </li>
      </ul></div>
     <div>
      <%= link_to "Register", sign_up_path, class:"btn btn-primary" %>        </li>

     </div></div>
    </div>
  </div>
</nav>